# Generated by ariadne-codegen
# Source: cow_py/subgraph/queries

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class Totals(BaseModel):
    totals: List["TotalsTotals"]


class TotalsTotals(BaseModel):
    tokens: Any
    orders: Any
    traders: Any
    settlements: Any
    volume_usd: Optional[Any] = Field(alias="volumeUsd")
    volume_eth: Optional[Any] = Field(alias="volumeEth")
    fees_usd: Optional[Any] = Field(alias="feesUsd")
    fees_eth: Optional[Any] = Field(alias="feesEth")
