# Generated by ariadne-codegen
# Source: cowdao_cowpy/subgraph/queries

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class LastDaysVolume(BaseModel):
    daily_totals: List["LastDaysVolumeDailyTotals"] = Field(alias="dailyTotals")


class LastDaysVolumeDailyTotals(BaseModel):
    timestamp: int
    volume_usd: Optional[Any] = Field(alias="volumeUsd")
